### PR TITLE
mrc-1950 add loading spinner feedback while content loads

### PR DESCRIPTION
**Pull request by hillalex**
The main thing that slows down loading content is actually loading the js for the plots (plotly and mathjs are by far the biggest contributors to bundle size.) So this PR:
* makes further use of the async component loading pattern, loading each of the impact/cost inner tabs asynchronously as well as the interventions step itself
* reduces the bundle size by
 a) creating a custom plotly module with only the bits we need
 b) using the `mathjs/number` entrypoint which excludes support for non-number data types and so reduces the size of mathjs by about 30% - see https://mathjs.org/docs/custom_bundling.html#numbers-only
* adds a loading spinner while async components are being loaded

This has definitely improved loading time, but unfortunately mathjs and plotly are still very big! Perhaps there are cleverer ways to manage bundle chunking/loading that can give further performance gains.

### CODE REVIEW

**Review by EmmaLRussell — COMMENTED** [review]
Approach all looks good to me, seem to be compile errors though?

**Comment by hillalex** [comment]
> Approach all looks good to me, seem to be compile errors though?

yeah sorry I fucked it up with a merge, just fixing

**Comment by hillalex** [comment]
ok try now!

**Review by EmmaLRussell — COMMENTED** [review]
This is building fine now, and looks great when loading existing project (minty spinner - nice!)

Getting console errors on create new project though, `cannot read property 'controlSections' of null`

**Comment by hillalex** [comment]
> Getting console errors on create new project though, `cannot read property 'controlSections' of null`

Thanks, it was because I moved fetching config to a later stage, but that included fetching settings. Have separated that out so settings are fetched before app mount, figure config as needed.

**Review by EmmaLRussell — APPROVED** [review]

**Pull request merged**
