### PR TITLE
mrc-2258 Add links to new user manuals

### PR DESCRIPTION
**Pull request by mwoodbri**
Add user guides, stored in resources folder [similar to HINT](https://github.com/mrc-ide/hint/tree/master/src/app/static/public/resources).

help

Much of the other help material is provided by mintr, but the front page content isn't and it seems more appropriate to serve PDFs as static content from the webapp itself. But I'm open minded.

### CODE REVIEW

**Review by EmmaLRussell — COMMENTED** [review]
Looks good, works great. I wonder if it would be better to open the guide in a new tab, since user is likely to want to have both it and the app open. Do you think it might merit a link (well, two links..) in the nav bar on the main region screen too, since people might not realise they need help until they get there!

**Comment by mwoodbri** [comment]
> Looks good, works great. I wonder if it would be better to open the guide in a new tab, since user is likely to want to have both it and the app open. Do you think it might merit a link (well, two links..) in the nav bar on the main region screen too, since people might not realise they need help until they get there!

Yep, good call. Links should always have opened in new page, and although it crossed my mind there's no reason not to include links in nav bar. Implemented so that it appears when you're not on the homepage - which fits well because the links are already available in the body there, and the accessibility link was only ever shown on that page.

toolbar

Only problem now is that the docs point to mint-dev.dide.ic.ac.uk! Will sort that post-review.

**Comment by EmmaLRussell** [comment]
Ah, well spotted on the link in the guides. Menu links working well, but got a failing front end test now.

**Comment by mwoodbri** [comment]
> Ah, well spotted on the link in the guides. Menu links working well, but got a failing front end test now.

I'm just making a small component to display these links in a short or long version. Will fix test in the process. Sorry - bit trigger-happy with re-assigning PR.

**Review by EmmaLRussell — APPROVED** [review]

**Pull request merged**
